### ISSUE TITLE
Issue with compilation

### ISSUE THREAD

**Issue by palenikj** [creativetimofficial/ct-vue-paper-dashboard-pro#111]
Compilation fails with error on macOS 10.15.15

TypeError: [BABEL] .../vue-paper-dashboard-2-pro-v2.3.0/src/main.js: Cannot read property 'android' of undefined (While processing: ".../vue-paper-dashboard-2-pro-v2.3.0/node_modules/@vue/babel-preset-app/index.js")

**Comment by toitx-sudobo** [comment]
I had the same problem. Is there a workaround for this?

**Comment by dragosct10** [comment]
Hi! Thanks for using our products. Please update the nodejs and npm to the latest version. 

Regards,
Dragos

**Comment by artilery** [comment]
Hi, on .babelrc you need to update the names:
change "es6.promise" to "es.promise"
and change "es7.object.entries" to "es.object.entries"

I hope this helps
