### ISSUE TITLE
[Bug] Many deprecated and ERROR

### ISSUE THREAD

**Issue by Yeolar** [creativetimofficial/ct-vue-paper-dashboard-pro#114]
### Version
1.1.1
### Reproduction link
https://github.com/Yeolar/errorlog/blob/master/2020-11-14T12_13_28_266Z-debug.log
### Operating System
MacOS
### Device
MacOS
### Browser & Version
npm 7.0.8
### Steps to reproduce
1. npm install  # meet package confliction
2. npm install --force  # meet ERR
### What is expected?
compile pass
### What is actually happening?
many errors, see: https://github.com/Yeolar/errorlog/blob/master/2020-11-14T12_13_28_266Z-debug.log

---

**Comment by dragosct10** [comment]
Hi, @Yeolar! Thanks for using our products. Did you have the BS 3 version? 

Regards,
Dragos

**Comment by sajadevo** [comment]
Hey there

We've updated the product and update most of the dependencies, please update to the latest version of the product.

Regards,
Sajad
