### ISSUE TITLE
[Bug] Failed to run "npm install"

### ISSUE THREAD

**Issue by bobolike123** [creativetimofficial/ct-vue-paper-dashboard-pro#121]
### Version
2.3.0
### Reproduction link
https://github.com/bobolike123/errorlog/blob/main/2021-08-18T08_17_22_183Z-debug.log
### Operating System
win10
### Device
win10 laptop
### Browser & Version
npm 7.14.0 ; node 10.13.0
### Steps to reproduce
npm install
### What is expected?
compile pass and install the node_modules successful
### What is actually happening?
errors occurred and failed to install modules see: https://github.com/Yeolar/errorlog/blob/master/2020-11-14T12_13_28_266Z-debug.log

---
### Additional comments
Is it due to the node version? I had succeed to run "npm install" to install modules for the other dashboard production which purchased on CreateTim

**Comment by sajadevo** [comment]
**Hey there**

We've updated the product and this issue is fixed now, please update to the latest version of the product.

Regards,
Sajad
