### ISSUE TITLE
Bootstrap 4 Integration

### ISSUE THREAD

**Issue by Failcookie** [creativetimofficial/ct-vue-paper-dashboard-pro#19]
I have seen some questions around about the BS4 Beta 1 integration, so I wanted to start a thread here and see how that looks. Is there a timeline right now for integrating Bootstrap 4? I am guessing it would be a pretty interesting transfer - I am for doing it manually, if anyone has any notes to share!

**Comment by cristijora** [comment]
Hi @Failcookie Creative-tim team is working on a converter from BS3 to BS4. When it's completed it (not sure when) pretty much all products will be converted to BS4 and I will be able to give more precise information on how to make this process more automatic.

There are many people interested in this topic/question on other products so I think it should be done this month or so.

**Comment by Failcookie** [comment]
Perfect! That is great to hear.

**Comment by tiagorosendo** [comment]
@cristijora  Vue Paper Dashboard Free was updated to BS4 1 week ago, when we'll receive that update ?

**Comment by alec-c4** [comment]
Any progress? Can we participate in beta testing?

**Comment by alec-c4** [comment]
@cristijora it looks like you ignore us :(

**Comment by cristijora** [comment]
Sorry for the long delay guys. Had to wait for the HTML version to be done first.
V2 was released with Bootstrap 4 and Vue CLI 3. Please leave me your usernames/emails here and I will send you the update on creative tim.

**Comment by alec-c4** [comment]
@cristijora alec@alec-c4.com

**Comment by gmmarc** [comment]
@cristijora gm.marc

Thanks!

**Comment by tiagorosendo** [comment]
@cristijora gschueler/ gschueler@braspag.com.br
