### ISSUE TITLE
NotFoundPage.vue doesn't look right

### ISSUE THREAD

**Issue by bbrewder** [creativetimofficial/ct-vue-paper-dashboard-pro#28]
If you look at the 404 page, it doesn't look quite right...

https://cristijora.github.io/paper-dashboard-pro/#/xxx

The navigation back to the site is off the page and in a bulleted list. It looks quite a bit out of character for the site.

**Comment by cristijora** [comment]
Hi @bbrewder Indeed the NotFound page is not inline with the rest of the pages.
The dashboard and the initial sketch files didn't really provide error pages. The current not found page was added so there is no blank page. We will try to provide some design for it in the next update.

**Comment by cristijora** [comment]
This was adressed in v2. https://demos.creative-tim.com/vue-paper-dashboard-pro/#/admin/inexistingpage
