### ISSUE TITLE
Loading Bar

### ISSUE THREAD

**Issue by abdullahonden** [creativetimofficial/ct-vue-paper-dashboard-pro#29]
I know that is not an issue but, it'd be great to see an option like "use loading bar" while switching between pages. Plugin below probably an easy option to use:

https://bosnaufal.github.io/vue2-loading-bar/

**Comment by cristijora** [comment]
Added `nprogress` to [v2.1.0](https://demos.creative-tim.com/vue-paper-dashboard-pro/documentation/changelog.html#_2-1-0-2018-08-09)
