### ISSUE TITLE
Charts Hover Tooltip

### ISSUE THREAD

**Issue by abdullahonden** [creativetimofficial/ct-vue-paper-dashboard-pro#3]
I wonder how can I show information when hover on charts, because this static mode doesn't give any information, people are use it like Google Analytics, hover the line or piechart and see the details. Here is an example:

<img width="733" alt="screen shot 2017-09-08 at 11 57 31" src="https://user-images.githubusercontent.com/3144843/30204157-108ceb30-948d-11e7-876a-2dd512dc10d9.png">

**Comment by cristijora** [comment]
Hi @abdullahonden The dashboard uses Chartist library for charts. Chartist usually exposes extra stuff via plugins. There is a tooltip plugin which you can find here https://github.com/tmmdata/chartist-plugin-tooltip 

The usage is quite simple
```js
npm install --save chartist-plugin-tooltip
```
And then where you initialize data for your charts
```
// import chartist if not imported
import Chartist from 'chartist'

// where you declare your chart data
          {
            labels: ['Jan', 'Feb', 'Mar', 'April', 'May', 'June'],
            series: [
              [230, 340, 400, 300, 570, 500, 800]
            ],
            plugins: [
              Chartist.plugins.tooltip()
            ]
          },
```

You can check out the chartist plugins [Here](https://gionkunz.github.io/chartist-js/plugins.html) as well as the [Documentation](https://gionkunz.github.io/chartist-js/getting-started.html)

The `ChartCard.vue` component in the Dashboard is just a wrapper which displays the chart so you can use everything chartist has to offer. In the end if new need more complex stuff or this library is not suited for your use case, you can use any other chart library which you have more experience with. Chartist is pretty easy to use and covers a lot of use-cases and it's pretty responsive

**Comment by cristijora** [comment]
Updated docs regarding [this issue](https://cristijora.github.io/paper-dashboard-pro/documentation.html?selectedKind=Charts&selectedStory=Line&full=0&down=1&left=1&panelRight=0&downPanel=REACT_STORYBOOK%2Freadme%2Fpanel) 
Last section from readme called `Chartist plugins`

**Comment by mlumbroso** [comment]
Hi,

From our testing, for it to work, it needs to be 
``` npm install --save chartist-plugin-tooltips``` with a 's'
And also import the CSS file for the plugin separately

Can you update documentation accordingly ? (or maybe enable it by default, I guess most people would need that no ?)

Thanks

**Comment by abdullahonden** [comment]
I agree, tooltips should come with default.

**Comment by cristijora** [comment]
Thanks for the feedback guys. Will add them as default to the demo charts and the repo.

**Comment by cristijora** [comment]
There is an update to [V2](https://www.creative-tim.com/product/vue-paper-dashboard-2-pro) which uses Vue Chart.js and has great tooltip options. You can check that in the example pages as well. If you don't have access to v2, let me know what are your usernames from creativetim and I will give access to it.
