### ISSUE TITLE
How to change radio button color?

### ISSUE THREAD

**Issue by abdullahonden** [creativetimofficial/ct-vue-paper-dashboard-pro#33]
Hi there,

As you know, theme comes with a default gray colored radio buttons. I take time and carefully tried to change it with css but couldn't manage how to change it. Possibly I'm missing something, this issue will help the possible similar requests.

---
Found it :) You can overwrite the _checkbox-radio.scss classes in your custom class like that:

```
.radio label::after { color: #fff; }
.radio label::before { color: #fff; }
.radio input[type="radio"]:not(:disabled):hover + label::before{ color:#333; }

```

**Comment by cristijora** [comment]
Added these to the v2 documentation as well https://demos.creative-tim.com/vue-paper-dashboard-pro/documentation/component-docs/radio.html#custom-radio-buttons
