### ISSUE TITLE
dropdown menu item

### ISSUE THREAD

**Issue by airguide** [creativetimofficial/ct-vue-paper-dashboard-pro#37]
in dev mode the sidebar dropdown menu item works i.e a list opens, in production it doesn't
Any workaround?

![image](https://user-images.githubusercontent.com/324225/37172866-1fb933dc-2323-11e8-88a1-0649af085436.png)

![image](https://user-images.githubusercontent.com/324225/37172881-2c0022b8-2323-11e8-9c27-3b58ee9fc3dd.png)

**Comment by cristijora** [comment]
Hi @airguide 

Thank you for using our product.
Could you please share a link to your website so we could look at?
We have have several application examples using this dashboard including the demo on the website and unfortunately didn't encounter such issues.

Most likely, it can be some css that overrides the normal behavior of the menu

**Comment by airguide** [comment]
sure, http://vericredit.herokuapp.com/ there is a login and password for it, Is there a way I can pass it?

**Comment by cristijora** [comment]
@airguide you can email me on joracristi@gmail.com

**Comment by xhijack** [comment]
the problem same with me. https://github.com/creativetimofficial/vue-paper-dashboard-pro/issues/45

**Comment by cristijora** [comment]
@xhijack @airguide There is a version 2 released. If you haven't upgraded or don't have access please leave your usersnames from creative tim and I will add an order to your accounts. The problem shouldn't persist in V2

**Comment by airguide** [comment]
hemal@mail.ru  

i don't see v2 in the downloads ((


>Sunday, August 12, 2018 4:01 PM +03:00 from Cristi Jora <notifications@github.com>:
>
>@xhijack @airguide There is a version 2 released. If you haven't upgraded or don't have access please leave your usersnames from creative tim and I will add an order to your accounts. The problem shouldn't persist in V2
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
hemal@mail.ru

**Comment by xhijack** [comment]
my account: xhijack

**Comment by cristijora** [comment]
@airguide @xhijack check your accounts guys

**Comment by airguide** [comment]
thanks, I got it :)


>Tuesday, August 14, 2018 4:46 PM +03:00 from Cristi Jora <notifications@github.com>:
>
>@airguide @xhijack check your accounts guys
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
hemal@mail.ru

**Comment by xhijack** [comment]
Thanks @cristijora
