### ISSUE TITLE
deploying problem with netlify

### ISSUE THREAD

**Issue by xhijack** [creativetimofficial/ct-vue-paper-dashboard-pro#45]
Hi,

I just deployed to netlify. But the dropdown didn't work https://blissful-lichterman-5668a0.netlify.com/
I have tried to deploy on VPS and running manual npm run build. Do you know what's the problem why the dropdown didn't work on netlify?

**Comment by xhijack** [comment]
thanks

**Comment by cristijora** [comment]
@xhijack Can you update to V2, and check if the problem still persists ?
If you don't have access to v2, let me know your exact username from creative tim and I will give you access to it.

**Comment by xhijack** [comment]
@cristijora my account in creative-tim: xhijack

**Comment by cristijora** [comment]
@xhijack Added v2 to your account 😃

**Comment by xhijack** [comment]
@cristijora I tried to deploy to netlify. here the result

https://wonderful-mayer-f7ed64.netlify.com/
