### ISSUE TITLE
Adding validation styles to DatePicker

### ISSUE THREAD

**Issue by chris838** [creativetimofficial/ct-vue-paper-dashboard-pro#46]
I've created a DatePicker input and successfully got it to validate and show the error message - great! However, the style of the picker does not match the other input components, e.g. the red text highlighting. How do I add this? If I set  ```class="form-control"``` on either the picker or the containing div (see code) I get an ugly offset effect (see screenshot).
```
      <div class="form-group">
        <label class="control-label">
          Date of birth
        </label>
        <div class="">
          <el-date-picker name="dob"
                          class="form-control"
                          v-model="model.dob"
                          v-validate="modelValidations.dob"
                          type="date"
                          placeholder="Select your date of birth"
                          :picker-options="datePickerOptions">
          </el-date-picker>
        </div>
        <small class="text-danger"
               v-show="dob.invalid">
            {{ getError('dob') }}
          </small>
      </div>
```

![image](https://user-images.githubusercontent.com/925254/40562766-9cf446f8-6062-11e8-858f-b16348fac4b8.png)

**Comment by cristijora** [comment]
Hi @chris838 Sorry for the long wait here!
The catch here is that the `form-control` class here applies to a wrapper div of the date picker. In order to make it work, you'd have to apply the form-control styles to the inner input of the date picker. You could do that with sass quite easily
```scss
.form-group .el-date-editor .el-input__inner {
 @extend .form-control;
 padding-left: 30px; //necessary so the text doesn't overlap with the icon
}
```

**Comment by gbrizu** [comment]
Hi @chris838  - Please, can you show me How do you make to add validation on this component? can you share your code??
