### ISSUE TITLE
Documentation link is broken

### ISSUE THREAD

**Issue by Sergeon** [creativetimofficial/ct-vue-paper-dashboard-pro#48]
This link:
http://vuejs.creative-tim.com/paper-dashboard-pro/documentation.html

is broken now (I found it in the application preview):
![image](https://user-images.githubusercontent.com/6699334/40914777-c6628b6e-67f9-11e8-8402-5d62d1d0651c.png)

However, I was able to find a working link:
https://demos.creative-tim.com/vue-paper-dashboard-pro/documentation.html?selectedKind=Welcome&selectedStory=to%20Vue%20Paper%20Dashboard%20PRO&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Factions%2Factions-panel

So I guess you guys just moved from one domain to another  and forgot to update the preview link. I don't know if maybe some other related links are broken too.

PS: Would be great to add the documentation link in the README of this gitHub repo too.  It is not listed in the **links** category nor in **useful links**.

**Comment by cristijora** [comment]
Hi @Sergeon Thanks for pointing out!
Indeed we moved some repositories under a single domain so it's easier to track everything. We will update the live demos with the correct links. Until then I added the docs link as per your suggestion in the README here.

**Comment by cristijora** [comment]
The docs link should be correct now on all repositories and dashboard versions.
