### ISSUE TITLE
Issues  in v2

### ISSUE THREAD

**Issue by sylvaincaillot** [creativetimofficial/ct-vue-paper-dashboard-pro#55]
Hi, 
I would like to use the new v2 version based on Bootsrrap 4 and CLI 3 but saw some issues:

For example, the arrow in the dropdown list does not appear properly: https://demos.creative-tim.com/vue-paper-dashboard-pro/?_ga=2.69685584.1714658699.1532666728-84536958.1530674135#/forms/extended

On a mobile display, the settings menu isnot shown anymore (icons on the top right of the navbar on a screen display).

Thank you for correcting this.

S.

**Comment by cristijora** [comment]
Hello @sylvaincaillot 

Thanks for reporting that. Indeed the select arrow is an issue. 
I will do a small update with css/component fixes in the upcoming week including the ones you mentioned.
As a quick fix you can go to
src/assets/sass/paper/plugins/element-ui/_plugin-select.scss Then change the `.el-input__icon` class to `.el-input__icon{ width: 30px; height: 40px; border-radius: 20px; } `

**Comment by cristijora** [comment]
These were addressed in [v2.1.0](https://demos.creative-tim.com/vue-paper-dashboard-pro/documentation/changelog.html#_2-1-0-2018-08-09)
