### ISSUE TITLE
Does an el-table have any properties so that rows are clickable and call a method when tapped?

### ISSUE THREAD

**Issue by iitgrad** [creativetimofficial/ct-vue-paper-dashboard-pro#56]
I'm not finding any documentation for this, but I may not be looking in the correct spot.

**Comment by kwatog** [comment]
Here's how I did mine

**Template**
`<el-table :data="queriedData" @row-click="rowClick" class="table-striped">`

**Script definition of rowClick**
`    methods: {
      rowClick (row) {
`

Element UI has its own documentation in the link below

http://element.eleme.io/#/en-US/component/table

**Comment by iitgrad** [comment]
awesome, that worked, thank you!!!!
