### ISSUE TITLE
updating chart data in v2

### ISSUE THREAD

**Issue by Fatflo** [creativetimofficial/ct-vue-paper-dashboard-pro#60]
Hello,
when I modify the data in this.activityChart.data (through an axios request in mounted/created event) on the Overview page, the chart is not updated.
The issue seems similar to what was discussed for v1 in this thread: https://github.com/creativetimofficial/ct-vue-paper-dashboard-pro/issues/49

Thanks,
Florian

**Comment by cristijora** [comment]
Hi @Fatflo 
Please check https://vue-chartjs.org/#/home?id=reactive-data from vue-chart.js
You might need to update the `LineChart, BarChart, PieChart` components to import this mixin. 
Here's a working example https://codesandbox.io/s/3j73wmjzq

**Comment by Fatflo** [comment]
Thanks @cristijora 
thanks for the help, unfortunately when I try to apply the same modifications I end up with the following error message in javascript console:
```
vue.runtime.esm.js?2b0e:587 [Vue warn]: Missing required prop: "chartData"
found in
---> <LineChart>
       <ChartCard> at src/components/UIComponents/Cards/ChartCard.vue
         <Overview> at src/components/Dashboard/Views/Dashboard/Overview.vue
           <DashboardContent> at src/components/Dashboard/Layout/Content.vue
             <DashboardLayout> at src/components/Dashboard/Layout/DashboardLayout.vue
               <App> at src/App.vue
                 <Root>
```

It would be really helpful if you could show an example directly based on paper dashboard v2, like the list of modifications required in LineChart, ChartCard, Overview in order to modify the data in one of the charts of the overview page.

Thanks !

**Comment by matdar** [comment]
Hi @Fatflo
Did you resolve this issue? I'm hitting exactly the same issue.... shame the charts weren't reactive by default.

Thanks
Matt

**Comment by Fatflo** [comment]
@matdar it's not resolved on my side...
