### ISSUE TITLE
Any tips on making the build output smaller?

### ISSUE THREAD

**Issue by kwatog** [creativetimofficial/ct-vue-paper-dashboard-pro#61]
Not really an issue but I'm looking for recommendation.

as it is, the build size is over 1mb. Considering I already removed most of the components save for the dashboard, chart and UI components, the output size is still relatively big. 

I'm using date-fns, btw as based on the web pack analyzer, moment js is taking a lot of space. I also import most of my components using the fat arrow (I dunno how you call that). 

Is there any tips? 

TIA

**Comment by cristijora** [comment]
Hello @kwatog 

Are you using v1 or v2 of the dashboard ?
If you're not too far into the app, I'd recommend using v2 and download the latest version. The latest version is quite optimized in terms of size. 

`chunk-vendors` file and `app` files are basically the ones that are always downloaded while the others are downloaded when you navigate to a page or a set of pages. 

<img width="539" alt="screen shot 2018-08-16 at 12 06 50 pm" src="https://user-images.githubusercontent.com/15955045/44199522-0bf59e00-a14d-11e8-9d1d-8d068b829618.png">

Here are a few tips to optmize stuff. 
1. Remove components/routes you don't use.
2. Async import all routes. Even better, group them together by use-cases/functionality with webpackchunckname See pic below.
<img width="947" alt="screen shot 2018-08-16 at 12 09 30 pm" src="https://user-images.githubusercontent.com/15955045/44199670-6131af80-a14d-11e8-8a12-1d2c1f59c936.png">

If you can give me more information about the version you use and maybe some extra stuff you implemented I could help. Moment.js is used by the chart plugins. If you don't use charts, you could simply remove the chart components and moment will be removed as well.

**Comment by kwatog** [comment]
thanks, @cristijora  Unfortunately, I already did what you said (save for Dashaboard, overview and login) but still encounter the same issue. It's not a big problem now but I'm afraid that as I continue to add new modules, the size will also increase.

I already migrated my app into v2, too.

Here's how my routes.js looks like
```
import DashboardLayout from '../components/Dashboard/Layout/DashboardLayout.vue'
import NotFound from '../components/GeneralViews/NotFoundPage.vue'
import Overview from 'src/components/Dashboard/Views/Dashboard/Overview.vue'
import Login from 'src/components/Dashboard/Views/Pages/Login.vue'
const ClientList = () => import('src/components/Clients/ClientList.vue')
const Calendar = () => import('src/components/Dashboard/Views/Calendar/CalendarRoute.vue')

```
I'm doing a customer management module which is loaded via ClientList

But I still get this.
```
This can impact web performance.
Assets:
  static/css/app.7555c961.css (454 KiB)
  static/js/chunk-3af3.4fe658a8.js (297 KiB)
  static/js/chunk-vendors.1cbeaeb4.js (844 KiB)
```
