### ISSUE TITLE
live demo is bs3, styling is different in actual product

### ISSUE THREAD

**Issue by scancmdr** [creativetimofficial/ct-vue-paper-dashboard-pro#62]
The download has font awesome styling on the paginated tables that do not look at all like the live demo. How can I get my purchased kit to look like the live demo?

I'm looking here:
https://demos.creative-tim.com/bs3/vue-paper-dashboard-pro/#/table-list/paginated

The table styling in my copy has this:
`<i class="fa fa-edit"></i>`

While the live demo has this:
`<i class="ti-pencil-alt"></i>`

**Comment by cristijora** [comment]
I know this is a very late reply but there are 2 versions. The link you pointed out is Vue Paper Dashboard on Bootstrap 3. The newest version is built on top of bootstrap 4. Link can be found here http://demos.creative-tim.com/vue-paper-dashboard-pro/
