### ISSUE TITLE
Top right menu in v2 disappears on smaller screens

### ISSUE THREAD

**Issue by sylvaincaillot** [creativetimofficial/ct-vue-paper-dashboard-pro#68]
Hi,
I think there is an issue with the top right menu (search bar, setting and bell icons) which totally disappears when you switch to a smaller screen size (tablet and smartphone in my case). 

![image](https://user-images.githubusercontent.com/4845910/46058132-1f147880-c1a5-11e8-9680-3c338c514276.png)

On a smaller screen such as smartphones, the top right menu is not reachable anymore:
![image](https://user-images.githubusercontent.com/4845910/46058163-57b45200-c1a5-11e8-8515-764924741be4.png)

I would expect something similar to the Now UI menu with 3 vertical dots:
![image](https://user-images.githubusercontent.com/4845910/46058219-b24dae00-c1a5-11e8-9c01-e59b1c70e4e9.png)

Thank you for your help

S.

**Comment by lennux23** [comment]
Hi, I just bought this template and I am facing the same problem. is there any update?

**Comment by cristijora** [comment]
@lennux23 @sylvaincaillot This issue has been fixed in latest update. To upgrade, just download the dashboard archive again from creative tim and follow [migration instructions](https://demos.creative-tim.com/vue-paper-dashboard-pro/documentation/migration-guide.html#from-2-1-0-to-2-2-0)
