### ISSUE TITLE
dropdown menus broken?

### ISSUE THREAD

**Issue by ecarrig** [creativetimofficial/ct-vue-paper-dashboard-pro#69]
the .zip file I downloaded after purchasing v2 is different than the live demo.

Has there been an update I missed?

live demo:
![capture](https://user-images.githubusercontent.com/19498632/46764470-86085600-ccaa-11e8-96f4-83240fcd19aa.JPG)

downloaded source files (N.B. vertical misaligment)
![capture1](https://user-images.githubusercontent.com/19498632/46764498-94567200-ccaa-11e8-9ac9-7330b78fde4e.JPG)

@sjennen

**Comment by cristijora** [comment]
@ecarrig Can you please check latest version (2.2.0) and see if the issue still persits for you ?
Latest version includes some updates and this one shouldn't appear there as well.
