### ISSUE TITLE
Change color el-collapse-item__header

### ISSUE THREAD

**Issue by CrzKev** [creativetimofficial/ct-vue-paper-dashboard-pro#72]
Dear,

I want to change the color of the header of an el-collapse item.

What I first did added a _collapse.scss in sass/paper/mixins but he didn't picked it up so I placed my mixin in the _button.scss temporarily.
Don't know where I have tot define the mixin so he would pick it up.
But I tried with placing it in another mixin for testing and can't get it to work.

Normal _collapse.scss:
.el-collapse-item{
	.collapse-primary { @include collapse-styles(yellow); }
    .el-collapse-item__header {
        // background-color: $pale-bg;
	}
}

In the mixin:
@mixin collapse-styles($element-color) {
  &.el-collapse-item__header {
    background-color: $element-color;
  }
}

In my html I place in the class next:
<el-collapse>
	<el-collapse-item class="el-collapse-item collapse-primary">

Probably this is out of scope but some help would be appreciated.

Kind regards
CrzKev

**Comment by cristijora** [comment]
Hey @CrzKev I know this is a very late answer but it seems that the issue you are describing refers to V1 of the dashboard which is no longer maintained unfortunately. I would recommend migrating to V2.
Here's the migration guide https://demos.creative-tim.com/vue-paper-dashboard-pro/documentation/migration-guide.html

If you don't have access to V2 please leave your email address from creative tim here in the comments and I will add V2 to your account.

**Comment by CrzKev** [comment]
No problem
My account hermans.kevin1988@gmail.com

Thank you

**Comment by CrzKev** [comment]
Thank you very much
