### ISSUE TITLE
vue-paper-dashboard-pro-2: Failed npm run dev

### ISSUE THREAD

**Issue by pmihova** [creativetimofficial/ct-vue-paper-dashboard-pro#74]
I bought Vue Paper Dashboard Pro 2.

Copied in clean directory
>npm install
>npm run dev

ERROR  Failed to compile with 2 errors

Syntax Error: /Users/myuser/Sites/myproject/dashboard/src/components/UIComponents/SidebarPlugin/SideBar.vue: Support for the experimental syntax 'dynamicImport' isn't currently enabled (87:35):

Syntax Error: SyntaxError: /Users/myuser/Sites/myproject/dashboard/src/routes/routes.js: Support for the experimental syntax 'dynamicImport' isn't currently enabled (5:24):

What am I doing wrong? 
Is a dependency missing?

Given documentation link in the readme.md is not correct.
https://cristijora.github.io/paper-dashboard-pro/documentation.html?selectedKind=Buttons&selectedStory=Default&full=0&down=1&left=1&panelRight=0&downPanel=tuchk4%2Freadme%2Fpanel

**Comment by pmihova** [comment]
Never mind. I figured this error out. I did not copy the hidden files under OSX.

**Comment by cristijora** [comment]
Great to hear that @pmihova that the issue was resolved. We did an upgrade yesterday and I'd recommend using the latest 2.2.0 version as it contains some fixes and improvements.
