### ISSUE TITLE
Page not scrolling to top

### ISSUE THREAD

**Issue by Fusseldieb** [creativetimofficial/ct-vue-paper-dashboard-pro#77]
So, I've purchased (material) dashboard pro, but when I scroll to the bottom of a long page and then try to go to a rather short page, it doesn't scroll back to the top, but instead leaves me with a blank page for me to scroll up.

Is there any solution to scroll always to the top on a new route? Would be great.

Thank you.

**Comment by Fusseldieb** [comment]
Solved it apparently. 
Disabling/Commenting "perfect-scrollbar" entirely (the initialization commands) solved that issue, now it goes to the top whenever a new route loads, but also now the default scrollbar is back, but that's fine for me, since I wanted that in the first place.

That custom scrollback was giving me headaches.

**Comment by cristijora** [comment]
Hey @Fusseldieb glad it was resolved for your and we did some minor updates on this template. I will close the issue.

PS: Do you have material dashboard or paper dashboard ? This repo is for Paper Dashboard issues.

**Comment by Fusseldieb** [comment]
> PS: Do you have material dashboard or paper dashboard ? This repo is for Paper Dashboard issues.

Material Dashboard, sorry about the confusion.
