### ISSUE TITLE
Visual Studio Plugin for Vue

### ISSUE THREAD

**Issue by zanhosit** [creativetimofficial/ct-vue-paper-dashboard-pro#80]
Is there a plugin for Visual Studio Plugin to use vue-paper-dashboard-pro in Visual Studio?

**Comment by cristijora** [comment]
hey @zanhosit I don't see any correlation between the template and visual studio usage. You could use https://github.com/vuejs/vetur extension for visual studio for Vue.js support but it's not really related to the template itself. Let me know if this helps.
